import mongoose, { Schema, Document } from 'mongoose';

export interface MembershipPlan {
  id: string;
  name: string;
  description?: string; // Description of the membership plan
  price: string; // e.g., "Free", "$19.99 / month"
  url: string; // Base Whop product page URL (affiliate link will be generated by appending ?a=woodiee)
  isPremium?: boolean; // Whether this is a premium/paid plan
}

export interface Webhook {
  id: string;
  name: string; // User-friendly name for the webhook (e.g., "Parlays Channel", "ML Bets")
  url: string; // Webhook URL
  type: 'whop' | 'discord'; // Webhook type
}

export type UserRole = 'companyOwner' | 'owner' | 'admin' | 'member';

export interface CompanyMembership {
  companyId: string; // Required, indexed
  alias: string; // Different alias per company
  role: UserRole; // Different role per company
  webhooks?: Webhook[]; // Different webhooks per company
  notifyOnSettlement?: boolean;
  onlyNotifyWinningSettlements?: boolean;
  optIn?: boolean; // Leaderboard opt-in per company

  // Follow offer settings (per company)
  followOfferEnabled?: boolean;
  followOfferPriceCents?: number;
  followOfferNumPlays?: number;
  followOfferPlanId?: string;
  followOfferCheckoutUrl?: string;

  joinedAt: Date; // When user joined this company
}

export interface IUser extends Document {
  // Primary key - unique per person
  whopUserId: string; // Unique index

  // Person-level data (same across all companies)
  whopUsername?: string;
  whopDisplayName?: string;
  whopAvatarUrl?: string;

  // Person-level settings (same across all companies)
  followingDiscordWebhook?: string;
  followingWhopWebhook?: string;

  // AutoIQ subscription status
  hasAutoIQ?: boolean;
  // AutoIQ mode: 'auto-trade' (mirror trades automatically) or 'notify-only' (manual execution)
  autoTradeMode?: 'auto-trade' | 'notify-only';

  // Company-specific memberships (array of company data)
  companyMemberships: CompanyMembership[];

  // Denormalized for performance: most recently accessed membership
  // This provides O(1) lookup for the common case (single company users)
  activeCompanyId?: string;
  activeMembership?: CompanyMembership;

  createdAt: Date;
  updatedAt: Date;
}

const WebhookSchema = new Schema<Webhook>({
  id: { type: String, required: true },
  name: { type: String, required: true },
  url: { type: String, required: true },
  type: { type: String, enum: ['whop', 'discord'], required: true },
}, { _id: false });

const CompanyMembershipSchema = new Schema<CompanyMembership>({
  companyId: { type: String, required: true, index: true },
  alias: { type: String, required: true, trim: true },
  role: {
    type: String,
    enum: ['companyOwner', 'owner', 'admin', 'member'],
    required: true,
    default: 'member'
  },
  webhooks: { type: [WebhookSchema], default: [] },
  notifyOnSettlement: { type: Boolean, default: false },
  onlyNotifyWinningSettlements: { type: Boolean, default: false },
  optIn: { type: Boolean, default: true },
  followOfferEnabled: { type: Boolean, default: false },
  followOfferPriceCents: { type: Number, min: 0 },
  followOfferNumPlays: { type: Number, min: 1 },
  followOfferPlanId: { type: String },
  followOfferCheckoutUrl: { type: String },
  joinedAt: { type: Date, default: Date.now },
}, { _id: false });

const UserSchema = new Schema<IUser>({
  whopUserId: {
    type: String,
    required: true,
    unique: true, // One document per person
    index: true
  },
  whopUsername: { type: String, trim: true },
  whopDisplayName: { type: String, trim: true },
  whopAvatarUrl: { type: String, trim: true },
  followingDiscordWebhook: { type: String, trim: true },
  followingWhopWebhook: { type: String, trim: true },
  hasAutoIQ: { type: Boolean, default: false },
  autoTradeMode: { type: String, enum: ['auto-trade', 'notify-only'], default: 'notify-only' },
  companyMemberships: {
    type: [CompanyMembershipSchema],
    default: []
  },
  activeCompanyId: { type: String, index: true },
  activeMembership: { type: CompanyMembershipSchema, _id: false },
}, {
  timestamps: true,
});

// Indexes for efficient queries
UserSchema.index({ 'companyMemberships.companyId': 1, 'companyMemberships.role': 1 });
UserSchema.index({ 'companyMemberships.companyId': 1, 'companyMemberships.optIn': 1 });
UserSchema.index({ 'companyMemberships.companyId': 1, whopUserId: 1 }, { unique: true, sparse: true });
UserSchema.index({ 'companyMemberships.followOfferPlanId': 1, 'companyMemberships.followOfferEnabled': 1 }); // For webhook lookup

export const User = (mongoose.models && mongoose.models.User) || mongoose.model<IUser>('User', UserSchema);
