import mongoose, { Schema, Document } from 'mongoose';

export interface MembershipPlan {
  id: string;
  name: string;
  description?: string; // Description of the membership plan
  price: string; // e.g., "Free", "$19.99 / month"
  url: string; // Base Whop product page URL (affiliate link will be generated by appending ?a=woodiee)
  isPremium?: boolean; // Whether this is a premium/paid plan
}

export interface Webhook {
  id: string;
  name: string; // User-friendly name for the webhook (e.g., "Parlays Channel", "ML Bets")
  url: string; // Webhook URL
  type: 'whop' | 'discord'; // Webhook type
}

export type UserRole = 'companyOwner' | 'owner' | 'admin' | 'member';

export interface IUser extends Document {
  alias: string;
  whopUserId: string;
  companyId?: string; // Company ID (manually entered, not auto-set from Whop)
  companyName?: string; // Company name (only for owners)
  companyDescription?: string; // Company description (only for owners)
  role: UserRole; // User role: companyOwner, owner, admin, or member
  whopName?: string; // Name of the Whop/company
  whopUsername?: string; // Username from Whop profile
  whopDisplayName?: string; // Display name from Whop profile
  whopAvatarUrl?: string; // Avatar URL from Whop profile
  webhooks?: Webhook[]; // Array of webhooks with names
  notifyOnSettlement?: boolean; // Whether to send notifications when trades are settled
  onlyNotifyWinningSettlements?: boolean; // If true, only send settlement webhooks for winning trades
  followingDiscordWebhook?: string; // Discord webhook URL for following page notifications
  followingWhopWebhook?: string; // Whop webhook URL for following page notifications
  membershipPlans?: MembershipPlan[]; // Array of membership plans for this Whop (only for owners)
  membershipUrl?: string; // Legacy: Primary membership URL (deprecated, use membershipPlans)
  optIn: boolean; // Only owners can opt-in to leaderboard
  hideLeaderboardFromMembers?: boolean; // Company owner setting to hide leaderboard from members
  followOfferEnabled?: boolean; // Whether follow offer is enabled
  followOfferPriceCents?: number; // Price in cents (e.g., 1000 = $10.00)
  followOfferNumPlays?: number; // Number of plays included in follow purchase
  followOfferPlanId?: string; // Whop plan ID (created automatically when settings saved)
  followOfferCheckoutUrl?: string; // Checkout URL with affiliate param
  stats: {
    winRate: number;
    roi: number;
    unitsPL: number;
    currentStreak: number;
    longestStreak: number;
  };
  createdAt: Date;
  updatedAt: Date;
}

const MembershipPlanSchema = new Schema<MembershipPlan>({
  id: { type: String, required: true },
  name: { type: String, required: true },
  description: { type: String },
  price: { type: String, required: true },
  url: { type: String, required: true },
  isPremium: { type: Boolean, default: false },
}, { _id: false });

const WebhookSchema = new Schema<Webhook>({
  id: { type: String, required: true },
  name: { type: String, required: true },
  url: { type: String, required: true },
  type: { type: String, enum: ['whop', 'discord'], required: true },
}, { _id: false });

const UserSchema = new Schema<IUser>({
  alias: { type: String, required: true, trim: true },
  whopUserId: { type: String, required: true, index: true },
  companyId: { type: String, index: true }, // Optional - must be manually entered
  companyName: { type: String, trim: true }, // Company name (only for owners)
  companyDescription: { type: String, trim: true }, // Company description (only for owners)
  role: { type: String, enum: ['companyOwner', 'owner', 'admin', 'member'], default: 'member', index: true },
  whopName: { type: String, trim: true },
  whopUsername: { type: String, trim: true },
  whopDisplayName: { type: String, trim: true },
  whopAvatarUrl: { type: String, trim: true },
  webhooks: { type: [WebhookSchema], default: [] }, // Array of webhooks with names
  notifyOnSettlement: { type: Boolean, default: false },
  onlyNotifyWinningSettlements: { type: Boolean, default: false }, // Only send settlement webhooks for winning trades
  followingDiscordWebhook: { type: String, trim: true }, // Discord webhook URL for following page notifications
  followingWhopWebhook: { type: String, trim: true }, // Whop webhook URL for following page notifications
  membershipPlans: { type: [MembershipPlanSchema], default: [] }, //only for owners
  membershipUrl: { type: String }, // Legacy field for backward compatibility
  optIn: { type: Boolean, default: false }, // Default false, only owners can opt-in
  hideLeaderboardFromMembers: { type: Boolean, default: false }, // Company owner setting to hide leaderboard from members
  followOfferEnabled: { type: Boolean, default: false }, // Whether follow offer is enabled
  followOfferPriceCents: { type: Number, min: 0 }, // Price in cents
  followOfferNumPlays: { type: Number, min: 1 }, // Number of plays included
  followOfferPlanId: { type: String }, // Whop plan ID
  followOfferCheckoutUrl: { type: String }, // Checkout URL with affiliate
  stats: {
    winRate: { type: Number, default: 0 },
    roi: { type: Number, default: 0 },
    unitsPL: { type: Number, default: 0 },
    currentStreak: { type: Number, default: 0 },
    longestStreak: { type: Number, default: 0 },
  },
}, {
  timestamps: true,
});

// Compound indexes for efficient queries
UserSchema.index({ companyId: 1, whopUserId: 1 }, { unique: true, sparse: true }); // Unique user per company (sparse since companyId can be null)
UserSchema.index({ companyId: 1, role: 1 }, { unique: true, partialFilterExpression: { $or: [ { role: 'owner' }, { role: 'companyOwner' } ], companyId: { $exists: true, $ne: null } } }); // Only 1 owner or companyOwner per companyId
UserSchema.index({ companyId: 1, optIn: 1, 'stats.roi': -1, 'stats.winRate': -1 }); // For company-scoped leaderboard
UserSchema.index({ role: 1, optIn: 1, companyId: 1 });
UserSchema.index({ followOfferPlanId: 1, followOfferEnabled: 1 }); // For webhook lookup by plan_id

export const User = (mongoose.models && mongoose.models.User) || mongoose.model<IUser>('User', UserSchema);

